Compiling stylesheets...
mkdir -p _build/html/ja/_static
python3 -m pysassc extensions/odoo_theme/static/style.scss _build/html/ja/_static/style.css
Compilation finished.
Starting build...
sphinx-build -c . -b html -D project_root= -D canonical_version= -D versions= -D languages= -D language=ja -D is_remote_build= -T -A google_analytics_key= -A plausible_script= -A plausible_domain= -j auto content _build/html/ja
Running Sphinx v4.3.2

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/runner/work/odoo-docs-ja/odoo-docs-ja/conf.py", line 116, in <module>
    import odoo.addons
  File "/home/runner/work/odoo-docs-ja/odoo-docs-ja/odoo/odoo/__init__.py", line 77, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sphinx/application.py", line 216, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sphinx/config.py", line 173, in read
    namespace = eval_config_file(filename, tags)
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sphinx/config.py", line 342, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/runner/work/odoo-docs-ja/odoo-docs-ja/conf.py", line 116, in <module>
    import odoo.addons
  File "/home/runner/work/odoo-docs-ja/odoo-docs-ja/odoo/odoo/__init__.py", line 77, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.10.18/x64/lib/python3.10/site-packages/sphinx/config.py", line 329, in eval_config_file
    exec(code, namespace)
  File "/home/runner/work/odoo-docs-ja/odoo-docs-ja/conf.py", line 116, in <module>
    import odoo.addons
  File "/home/runner/work/odoo-docs-ja/odoo-docs-ja/odoo/odoo/__init__.py", line 77, in <module>
    import PyPDF2
ModuleNotFoundError: No module named 'PyPDF2'

make: *** [Makefile:57: html] Error 2
